# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcwxMainFrame(wx.Frame):
#!XRCED:begin-block:xrcwxMainFrame.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcwxMainFrame.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "wxMainFrame")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.wxSelectTargetCombo = xrc.XRCCTRL(self, "wxSelectTargetCombo")
        self.wxMediaFileCombo = xrc.XRCCTRL(self, "wxMediaFileCombo")
        self.wxIPTextctrl = xrc.XRCCTRL(self, "wxIPTextctrl")
        self.wxPortTextctrl = xrc.XRCCTRL(self, "wxPortTextctrl")

        self.Bind(wx.EVT_BUTTON, self.OnButton_wxOpenTargetButton, id=xrc.XRCID('wxOpenTargetButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_wxPlayTargetButton, id=xrc.XRCID('wxPlayTargetButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_wxFullscreenTargetButton, id=xrc.XRCID('wxFullscreenTargetButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_wxServerStartButton, id=xrc.XRCID('wxServerStartButton'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_wxServerStopButton, id=xrc.XRCID('wxServerStopButton'))

#!XRCED:begin-block:xrcwxMainFrame.OnButton_wxOpenTargetButton
    def OnButton_wxOpenTargetButton(self, evt):
        # Replace with event handler code
        print "OnButton_wxOpenTargetButton()"
#!XRCED:end-block:xrcwxMainFrame.OnButton_wxOpenTargetButton        

#!XRCED:begin-block:xrcwxMainFrame.OnButton_wxPlayTargetButton
    def OnButton_wxPlayTargetButton(self, evt):
        # Replace with event handler code
        print "OnButton_wxPlayTargetButton()"
#!XRCED:end-block:xrcwxMainFrame.OnButton_wxPlayTargetButton        

#!XRCED:begin-block:xrcwxMainFrame.OnButton_wxFullscreenTargetButton
    def OnButton_wxFullscreenTargetButton(self, evt):
        # Replace with event handler code
        print "OnButton_wxFullscreenTargetButton()"
#!XRCED:end-block:xrcwxMainFrame.OnButton_wxFullscreenTargetButton        

#!XRCED:begin-block:xrcwxMainFrame.OnButton_wxServerStartButton
    def OnButton_wxServerStartButton(self, evt):
        # Replace with event handler code
        print "OnButton_wxServerStartButton()"
#!XRCED:end-block:xrcwxMainFrame.OnButton_wxServerStartButton        

#!XRCED:begin-block:xrcwxMainFrame.OnButton_wxServerStopButton
    def OnButton_wxServerStopButton(self, evt):
        # Replace with event handler code
        print "OnButton_wxServerStopButton()"
#!XRCED:end-block:xrcwxMainFrame.OnButton_wxServerStopButton        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('GUI.xrc')
